image:
  repository: principlestudios.azurecr.io/principle-tools
ingress:
  annotations:
    cert-manager.io/cluster-issuer: principle-tools-issuer
  enabled: true

resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 50Mi
